Implemented: basic structure of app (#1-boiler-template)
hotwax/napita-flow-manager pull request #3
Opened 2024-03-13 06:12 UTC by Ritika-Patel08

### Related Issues

Related issue  #1 

### Short Description and Why It's Useful

Created basic structure for app.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2024-03-14 10:13 UTC, amansinghbais commented on .firebaserc
> +          "dev-<app-name>"
Add app name here

2024-03-14 10:13 UTC, amansinghbais commented on .github/PULL_REQUEST_TEMPLATE.md
> +Closes #
Change this to Related Issue

2024-03-14 10:13 UTC, amansinghbais commented on README.md
> +`git clone <your repository url>`
Add repo url here

2024-03-15 09:06 UTC, ymaheshwari1 requested changes

2024-03-15 09:06 UTC, ymaheshwari1 commented on .env.example
> +VUE_APP_LOGIN_URL="http://launchpad.hotwax.io/login"
Remove VUE_APP_LOGIN_URL from env

2024-03-15 09:06 UTC, ymaheshwari1 commented on .github/workflows/firebase-hosting-merge.yml
> +# This file was auto-generated by the Firebase CLI
Remove the firebase workflows as this will get triggered on merge and as we do not have firebase in-place so this will always fail.

2024-03-15 09:06 UTC, ymaheshwari1 commented on tests/e2e/.eslintrc.js
> +module.exports = {
Remove all test related files and its corresponding packages.

2024-03-18 14:06 UTC, merged