Implemented: login and logout functionality and used pinia instead for vuex store #4
hotwax/napita-flow-manager pull request #8
Opened 2024-03-22 11:55 UTC by Ritika-Patel08

### Related Issues

Related Issue #4 

### Short Description and Why It's Useful

- Implemented login and logout functionality.
- Implemented store using pinia for state management 
- Removed the vuex store and its related files.
- Removed dxp components and related fucntions 

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/napita-flow-manager#contribution-guideline)

2024-03-26 13:30 UTC, ymaheshwari1 requested changes

2024-03-26 13:30 UTC, ymaheshwari1 commented on package.json
> +    "pinia": "^2.1.7",
Remove vuex and vuex-persistedstate

2024-03-26 13:30 UTC, ymaheshwari1 commented on src/api/index.ts
> +// axios.interceptors.request.use((config: any) => {
We need to pass the token when making api calls using `api` method

2024-03-26 13:30 UTC, ymaheshwari1 commented on src/api/index.ts
> +      return axios(config);
Improve indentation

2024-03-28 08:45 UTC, Ritika-Patel08 commented on src/api/index.ts
> +      return axios(config);
done.

2024-03-28 08:46 UTC, Ritika-Patel08 commented on package.json
> +    "pinia": "^2.1.7",
Done.

2024-03-28 11:06 UTC, amansinghbais commented on src/App.vue
> +const router = useRouter();
Remove unused router declaration.

2024-03-28 11:06 UTC, amansinghbais commented on src/main.ts
>  import { showToast } from '@/utils'
Remove showToast import if not used.

2024-03-28 11:06 UTC, amansinghbais commented on src/router/index.ts
> +
Remove this unwated space.

2024-03-28 11:06 UTC, amansinghbais commented on src/router/index.ts
> +  },
Remove unwanted change

2024-03-28 11:06 UTC, amansinghbais commented on src/router/index.ts
> +//   authGuard(to, from, next);
Remove this if not needed.

2024-03-28 11:06 UTC, amansinghbais commented on src/services/UserService.ts
> +  //let token = ""
Remove token variable if not needed

2024-04-01 05:17 UTC, amansinghbais commented on src/api/index.ts
> +      return axios(config);
Not fixed re-check

2024-04-01 05:17 UTC, amansinghbais commented on src/components/Tabs.vue
> +
Remove unnecessary space.

2024-04-01 05:17 UTC, amansinghbais commented on src/store/user.ts
> +      instanceUrl: "",
Follow consistent structure for empty string declaration.

2024-04-01 05:17 UTC, amansinghbais commented on src/views/Settings.vue
> +              <ion-card-subtitle>{{ translate("demo-user") }}</ion-card-subtitle>
No need to translate this.

2024-04-01 05:17 UTC, amansinghbais commented on src/views/Settings.vue
> +            <!-- <ion-avatar slot="start" v-if="userProfile?.partyImageUrl">
Remove following code if not required.

2024-04-01 05:17 UTC, amansinghbais commented on src/store/user.ts
> +        console.error('Error logging out:', err);
Check whether logger is implemented in app or not? If implemented, use that.

2024-04-02 04:00 UTC, amansinghbais approved these changes

2024-04-02 05:01 UTC, ymaheshwari1 requested changes

2024-04-02 05:01 UTC, ymaheshwari1 commented on src/services/UserService.ts
> +    return Promise.reject("Sorry, login failed. Please try again");
I think we should allow user to login into the app without having expiration time check, simply login the user into the app without expirationTime.

2024-04-02 05:01 UTC, ymaheshwari1 commented on src/views/Login.vue
> +    <ion-page>
Indentaion Issue

2024-04-02 05:01 UTC, ymaheshwari1 commented on src/views/Settings.vue
> +              <ion-card-subtitle>demo-user</ion-card-subtitle>
Make this dynamic.

2024-04-02 05:01 UTC, ymaheshwari1 commented on src/store/user.ts
> +      try {
Add loader to let user know that something is going on in the background for all actions wherever required.

2024-04-02 05:01 UTC, ymaheshwari1 commented on src/api/index.ts
> +  document.cookie = `x-csrf-token=${csrfToken}`
Remove this code related to csrf token.

2024-04-02 07:07 UTC, ymaheshwari1 requested changes

2024-04-02 07:07 UTC, ymaheshwari1 commented on src/views/Login.vue
> +  }).catch(err => err)
Improve indentation

2024-04-02 07:07 UTC, ymaheshwari1 commented on src/store/user.ts
> +      emitter.emit('presentLoader', { message: 'Logging in', backdropDismiss: false })
Move this loader to the calling method

2024-04-02 10:43 UTC, ymaheshwari1 requested changes

2024-04-02 10:43 UTC, ymaheshwari1 commented on src/store/user.ts
> +        emitter.emit('dismissLoader')
We have not emitted the presentLoader function before dismissing.

2024-04-02 10:50 UTC, ymaheshwari1 approved these changes

2024-04-02 10:50 UTC, merged