Implemented: logic to fetch groups and its processes (#7-groups)
hotwax/napita-flow-manager pull request #9
Opened 2024-04-03 05:26 UTC by Ritika-Patel08

### Related Issues

Related Issue #7 

### Short Description and Why It's Useful

- fetched the process groups and its related processes.

### Screenshots of Visual Changes before/after (If There Are Any)

![image](https://github.com/hotwax/napita-flow-manager/assets/83332530/ea5b8d03-3235-4ea9-9d9f-ddae5df641d1)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/napita-flow-manager#contribution-guideline)

2024-04-03 05:42 UTC, amansinghbais commented on src/components/Tabs.vue
> +          <ion-label>{{ translate("Process") }}</ion-label>
Change tab name to "Group"

2024-04-03 05:44 UTC, amansinghbais commented on src/services/GroupService.ts
> +const FetchProcessGroups = async (root: any): Promise<any> => {
```suggestion
const etchProcessGroups = async (root: any): Promise<any> => {
```

2024-04-03 06:01 UTC, amansinghbais commented on src/services/GroupService.ts
> +    console.log(err);
Use logger instead of using console. Also check for other places

2024-04-03 06:01 UTC, amansinghbais commented on src/store/groups.ts
> +				root:'a3229852-0187-1000-8abc-9e42ca1734f2'
Instead of defining root here, hardcode it in the fetchProcessGroup action.

2024-04-03 06:01 UTC, amansinghbais commented on src/store/groups.ts
> +				const processGroups = await GroupService.FetchProcessGroups(this.root);
Improve Indentation.

2024-04-03 06:01 UTC, amansinghbais commented on src/theme/variables.css
> +.empty-state > img {
Use empty state css from the apps-theme

2024-04-03 06:01 UTC, amansinghbais commented on src/views/groups.vue
> +let CurrentProcessGroup = ref('') as any;
Check whether there is a need to define it using ref. If data is fetched computed property.

2024-04-03 06:01 UTC, amansinghbais commented on src/views/groups.vue
> +  await fetchProcessGroups();
Call action here directly, instead of calling a method.

2024-04-03 07:30 UTC, amansinghbais commented on src/components/Tabs.vue
> +import { settingsOutline, personOutline } from "ionicons/icons";
Arrange alphabetically.

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +import { computed, ref } from "vue";
Remove unused ref.

2024-04-03 09:02 UTC, amansinghbais commented on src/components/Tabs.vue
> +          <ion-label>{{ translate("Group") }}</ion-label>
Make the tab as Groups

2024-04-03 09:02 UTC, amansinghbais commented on src/router/index.ts
> +        path: 'group',
```suggestion
        path: 'groups',
```

2024-04-03 09:02 UTC, amansinghbais commented on src/services/GroupService.ts
> +import logger from '../logger';
Why are we importing logger using ../ path notation instead of using @/

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +        <ion-title>Napita Flow Manager</ion-title>
Translate static texts

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +          <div v-if="currentProcessBygroupDetail.length > 0">
```suggestion
          <div v-if="currentProcessBygroupDetail.length">
```

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +              <ion-radio-group >
We can remove ion-radio-group since we are not using ion-radio here

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +const currentProcessBygroupDetail = computed(() => groupStore.getCurrentGroupProcesses)
```suggestion
const currentGroupProcesses = computed(() => groupStore.getCurrentGroupProcesses)
```

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +const CurrentProcessGroup = computed(() => groupStore.getCurrentGroup);
```suggestion
const currentProcessGroup = computed(() => groupStore.getCurrentGroup);
```

2024-04-03 09:02 UTC, amansinghbais commented on src/views/groups.vue
> +  await fetchProcessByGroups(selectedProcessGroupId);
Directly call action here instead of calling function.

2024-04-03 10:58 UTC, amansinghbais commented on src/services/GroupService.ts
> +const fetchProcessByGroups = async (root: any): Promise<any> => {
```suggestion
const fetchProcessByGroups = async (groupId: any): Promise<any> => {
```

2024-04-03 10:58 UTC, amansinghbais commented on src/store/groups.ts
> +      try{
```suggestion
      try {
```

2024-04-03 10:58 UTC, amansinghbais commented on src/views/groups.vue
> +                <!-- <p class="overline">{{ group.id }}</p> -->
Why is this line commented?

2024-04-03 11:24 UTC, amansinghbais commented on src/router/index.ts
> +
Remove unnecessary space.

2024-04-03 11:24 UTC, amansinghbais commented on src/views/groups.vue
> +                <ion-accordion v-for="(process, index) in currentGroupProcesses" :key="index" >
improve intendation.

2024-04-03 11:24 UTC, amansinghbais commented on src/views/groups.vue
> +        <ion-menu-button slot="start" />
Remove this ion-menu-button if not used.

2024-04-05 11:32 UTC, ymaheshwari1 requested changes

2024-04-05 11:32 UTC, ymaheshwari1 commented on src/views/groups.vue
> +            <p>No process found for {{ currentProcessGroup.name }} .</p>
Add support for internationalization.

2024-04-05 11:32 UTC, ymaheshwari1 commented on src/views/groups.vue
> +const processGroups = computed(() =>groupStore.getProcessGroups);
```suggestion
const processGroups = computed(() => groupStore.getProcessGroups);
```

2024-04-05 11:32 UTC, ymaheshwari1 commented on src/store/groups.ts
> +    async fetchProcessByGroups(id: any) {
```suggestion
    async fetchProcessByGroup(id: string) {
```

2024-04-05 11:32 UTC, ymaheshwari1 commented on src/store/groups.ts
> +    setcurrentProcessGroup(processGroup: any) {
```suggestion
    setCurrentProcessGroup(processGroup: any) {
```

2024-04-26 05:48 UTC, merged